OBJS:= $(OBJS) arch/$(ARCH)/boot.o arch/$(ARCH)/kernel.o arch/$(ARCH)/sys/system.o arch/$(ARCH)/drivers/vga/vga.o arch/$(ARCH)/sys/isr.o arch/$(ARCH)/sys/gdt.o
OBJS:= $(OBJS) arch/$(ARCH)/libk/string.o arch/$(ARCH)/libk/stdio.o arch/$(ARCH)/sys/gdts.o arch/$(ARCH)/sys/idt.o arch/$(ARCH)/sys/idts.o arch/$(ARCH)/libk/cpuid.o 
OBJS:= $(OBJS) arch/$(ARCH)/sys/isrs.o arch/$(ARCH)/sys/irq.o arch/$(ARCH)/sys/irqs.o arch/$(ARCH)/sys/8253.o arch/$(ARCH)/sys/8259.o
OBJS:= $(OBJS) arch/$(ARCH)/drivers/input/8042.o arch/$(ARCH)/sys/cpu.o arch/$(ARCH)/sys/panic.o arch/$(ARCH)/mm/kframe.o arch/$(ARCH)/mm/kheap.o 
OBJS:= $(OBJS) arch/$(ARCH)/mm/kmalloc_early.o arch/$(ARCH)/mm/paging.o arch/$(ARCH)/usr/shell.o arch/$(ARCH)/sys/a20.o arch/$(ARCH)/sys/a20s.o arch/$(ARCH)/drivers/vbe/vbe.o
OBJS:= $(OBJS) arch/$(ARCH)/drivers/gfx.o arch/$(ARCH)/sys/tss.o arch/$(ARCH)/sys/tsss.o arch/$(ARCH)/mm/page.o arch/$(ARCH)/fs/fs.o arch/$(ARCH)/fs/initrd.o