OBJS:= $(OBJS) arch/$(ARCH)/boot.o arch/$(ARCH)/sys/system.o arch/$(ARCH)/vga/vga.o arch/$(ARCH)/sys/isr.o arch/$(ARCH)/sys/gdt.o
OBJS:= $(OBJS) arch/$(ARCH)/libc/string.o arch/$(ARCH)/sys/gdts.o arch/$(ARCH)/sys/idt.o arch/$(ARCH)/sys/idts.o arch/$(ARCH)/libc/cpuid.o 
OBJS:= $(OBJS) arch/$(ARCH)/sys/isrs.o arch/$(ARCH)/sys/irq.o arch/$(ARCH)/sys/irqs.o arch/$(ARCH)/sys/timer.o arch/$(ARCH)/keyboard/keyboard.o
OBJS:= $(OBJS) arch/$(ARCH)/sys/cpu.o